<?php
/** @var \Shvorak\Action\Block\Adminhtml\AssignProducts $block */
/** @var \Shvorak\Action\Block\Adminhtml\Tab\ProductGrid $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="action_products" data-form-part="shvorak_action_form" id="in_action_products" value=""  />
<script type="text/x-magento-init">
    {
        "*": {
            "Shvorak_Action/js/assign-products": {
                "selectedProducts":  <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
